@api = http://localhost:8080


### cuota
GET {{api}}/api/cuotas

### cuota
GET {{api}}/api/cuotas/test

### cuota
GET {{api}}/api/cuotas/hoy

### cuota
GET {{api}}/api/cuotas/bycustomer/1

### cuota
GET {{api}}/api/cuotas/deudas/1

### cuota
GET {{api}}/api/cuotas/pagados/1

### Create cuota
POST {{api}}/api/cuotas
Content-Type: application/json

{
  "customerId": 2,
  "modalidad": "Musculacion",
  "tipo": "Semanal",
  "fecha": "2022-08-20T04:00:00.000Z",
  "monto": 555
}

### get cuota
GET {{api}}/api/cuotas/2

### delete cuota
DELETE {{api}}/api/cuotas/1


### update cuota
PUT {{api}}/api/cuotas/2
Content-Type: application/json

{
  "title": "Editado Tesdadst",
  "description": "edit",
  "published":true
}
